### ISSUE TITLE
AVP2 Y Axis/Vertical movement

### ISSUE THREAD

**Issue by MiraakThuri** [elishacloud/dinputto8#18] opened 2023-01-01 06:19 UTC
Hey, by default AVP2 (Alien versus Predator 2) have rly janky mouse movements on the Y axis, it's not straight at all (X/horizontal is fine)
PCgamingwiki suggested some older and more obscure wrappers, but they don't correctly fix the issue

If i try to use your wrapper, X axis movement still work correctly, i have to rebind the controls that used mouse buttons and they work but vertical/Y axis movement no longer work at all, nothing happen when moving my mouse vertically

do you know if that could be fixed ?
Thx for your work

**Comment by elishacloud** [comment] 2023-09-14 16:04
Can you try using the latest version to see if it helps?

**Comment by MiraakThuri** [comment] 2023-09-15 12:35
Ok so just tried the last version, it's still the same problem, Y axis does not work at all
then i tried the debug version and Y axis worked, however i don't know if this version is only here for logging or if it also provide effects ingame (my old mouse is broken and my current mouse is low pooling rate so the Y axis jankiness is not rly noticeable) 
here is the log file:
[dinput.log](https://github.com/elishacloud/dinputto8/files/12619314/dinput.log)

**Comment by MiraakThuri** [comment] 2024-01-04 18:27
Update: Y axis mouvement does work again with your wrapper if i disable hardware cursor in the game settings

my issue is the same as this one https://github.com/elishacloud/dxwrapper/issues/30 
wich gave me the idea to disable hardware cursor by looking at the answers

but my high dpi mouse is corrently broken and im using an old pretty basic one so i can't check if the Y axis movement jitter bug is fixed

PS: i tried to use https://github.com/geeky/dinput8wrapper along with your wrapper as you suggested to get dinput8 raw mouse movement but for me it just does not work (all controls get erased and can't be rebinded)

**Comment by elishacloud** [comment] 2024-06-15 23:21
Closing this as a duplicate of:  [elishacloud/dxwrapper#30](https://github.com/elishacloud/dxwrapper/issues/30)

**Closed as completed by elishacloud** 2024-06-15 23:21 UTC
